---
- name: "Configure VPN Client: {{ name }}"
  template:
    src: client.conf
    dest: "/etc/openvpn/client/{{ name }}.conf"
  vars:
   vpn_dev: "{{ dev }}"
   vpn_server: "{{ server }}"
   vpn_port: "{{ port }}"
   vpn_ca: "{{ ca }}"
   vpn_name: "{{ name }}"

- name: "Configure VPN Auth: {{ name }}"
  template:
    src: auth.client
    dest: "/etc/openvpn/client/auth.{{ name }}"
  vars:
    vpn_username: "{{ username }}"
    vpn_password: "{{ password }}"

- name: "Set firewall zone: {{ name }}"
  firewalld:
    zone: "{{ zone }}"
    interface: "{{ dev }}"
    state: enabled
    permanent: yes
    immediate: yes
