---
- name: Key MD5
  shell: "openssl rsa -noout -modulus -in {{ key }} | openssl md5"
  register: key_md5 

- name: Debug key md5
  debug:
    var: key_md5.stdout

- name: Cert MD5
  shell: "echo '{{ cert }}' | openssl x509 -noout -modulus | openssl md5"
  register: cert_md5

- name: Debug cert md5
  debug:
    var: cert_md5.stdout

- name: Check cert matches key
  assert:
    that: key_md5.stdout == cert_md5.stdout

- name: Install SSL certificate
  copy:
    content: "{{ cert }}"
    dest: "{{ dest }}"
