---
- name: Configure Firewall Ports
  firewalld:
    zone: "{{ zone }}"
    port: "{{ port }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items: "{{ ports }}"
  loop_control:
    loop_var: port
